name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set date
      run: date +%s > date
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/nginx-with-stream:latest && docker tag ${{ secrets.DOCKER_USER }}/nginx-with-stream:latest ${{ secrets.DOCKER_USER }}/nginx-with-stream:$(cat date)
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
    - name: Docker Publish
      run: docker push ${{ secrets.DOCKER_USER }}/nginx-with-stream:latest
    - name: Docker Publish
      run: docker push ${{ secrets.DOCKER_USER }}/nginx-with-stream:$(cat date)
