name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag marine789/nginx-with-stream:alpine-$(date +%s)
    - name: Docker Publish
      uses: manusa/actions-publish-docker@v1.0.1
      with:
        # Name of the Docker image
        name: nginx-with-stream
        # Tag for the Docker image
        # tag: # optional
        # Script body to compute tag name for the Docker image, has context as the main function argument
        tag script: alpine-$(date +%s)
        # Username for Docker registry
        username: marine789
        # Password for Docker registry
        password: K31thusaD789
        # Registry URL
        # registry: # optional
